### ISSUE TITLE
Invalid percent encoded string exception

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/vcf-js#43]
File https://ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo_sapiens/by_assembly/GRCh37/vcf/GRCh37.variant_call.vcf.gz

Code https://github.com/GMOD/vcf-js/blob/master/src/parse.js#L194-L219

Produces the Invalid percent encoded string exception

Any particular reason for this limited set of percent encoded charpoints?

**Comment by garrettjstevens** [comment]
Those percent encodings are from the VCF spec (section 1.2) https://samtools.github.io/hts-specs/VCFv4.3.pdf

It looks like the offending line in that VCF uses `%20` to encode spaces in the INFO column, but it should just use literal spaces, as they are allowed in the INFO column.

We could maybe just ignore invalid percent-encodings, but that gets a bit tricky since the percent sign itself is supposed to be percent-encoded, so technically any time you see a percent sign it should be part of one of the valid percent-encodings.

**Comment by cmdcolin** [comment]
I don't interpret that section say those are the only valid percent encodings although it's vague

**Comment by cmdcolin** [comment]
Id either add full urldecoding and or allow %20

Probably I'd also not throw as this is just a very strict consequence, it's better to make a best effort to display the data imo

**Comment by rbuels** [comment]
Is it because multi byte characters mess up some of the byte arithmetic?

**Comment by cmdcolin** [comment]
There is not really any byte arithmetic, this is just vcf-js and not tabix-js

**Comment by garrettjstevens** [comment]
Yeah, it's just so you don't use reserved characters that could mess up the parsing.

I've given it some thought, and I'm starting to think that percent-decoding doesn't really belong in vcf-js. Or maybe it's an option but doesn't happen by default. The VCF spec says that special characters should be encoded, but doesn't give any guidance on decoding. Other tools I've looked at (like htslib/bcftools) just return the strings as-is with no decoding. So for our case, JBrowse would be able to decide if or how to do decoding for any INFO or FORMAT strings it got back from the parser. This way vcf-js can stay simple and not throw unnecessary errors or make unnecessary assumptions.

I realize I'm the one who added percent-decoding originally, but the reasons I can remember from back then don't seem valid now.

**Comment by cmdcolin** [comment]
But then instead of just an at-once decode it would have to decode tons of tiny strings from the broken up info object?

**Comment by garrettjstevens** [comment]
Internally it already decodes each broken up INFO and FORMAT piece individually. You can't decode the whole string at once, since you can't e.g. decode `%2C` to `,` and then split on `,`, you have to split first.

You'd only have to worry about decoding INFO and FORMAT entries that were of type String or unknown, though.

**Comment by cmdcolin** [comment]
Good point. Well, even still, why would we have any hesitation to perform the decoding in vcf-js? If it get's kicked to jbrowse or an end-user, it will have to do a lot of work to handle this properly

**Comment by garrettjstevens** [comment]
Because the encoding is vague, and decoding isn't even addressed in the spec. I'd rather just pass things on as-is and let the end-user decide what is "the right way" to handle it for their application.

**Comment by cmdcolin** [comment]
Hm. Well, I can't disagree that it's not well defined.

**Comment by cmdcolin** [comment]
There is a line in the code that says this


    thisValue = this._percentDecode(formatValue).split(',')


Does this mean that percent decoding is essential to a functionality or is this an instance where it should not be percent decoded in the first place

**Comment by garrettjstevens** [comment]
Pretty sure that's a bug, it should split first and then percent-decode.

**Comment by cmdcolin** [comment]
Alrighty we will just not do any percent decoding
